name: Pipeline

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_OWNER: StanleyProjects
      GITHUB_REPO: AndroidExtension.UserInterface
      telegram_bot_id: ${{secrets.TELEGRAM_BOT_ID}}
      telegram_bot_token: ${{secrets.TELEGRAM_BOT_TOKEN}}
      telegram_chat_id: ${{secrets.TELEGRAM_CHAT_ID_COMMON}}
      RESOURCES_PATH: buildSrc/src/main/resources
    steps:
      - run: |
          echo "PR_NUMBER=$(jq -r .pull_request.number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "PR_SOURCE_BRANCH=$(jq -r .pull_request.base.ref $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "GIT_SOURCE_BRANCH=$(jq -r .pull_request.head.ref $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=$(jq -r .pull_request.head.sha $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
      - run: git clone -q --depth=1 --branch=$GIT_SOURCE_BRANCH https://github.com/$GITHUB_OWNER/$GITHUB_REPO.git repository
      - working-directory: repository
        run: /bin/bash $RESOURCES_PATH/bash/workflow/dev.sh
