name: Pipeline

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_OWNER: StanleyProjects
      GITHUB_REPO: AndroidExtension.UserInterface
      RESOURCES_PATH: buildSrc/src/main/resources
    steps:
      - run: |
          echo "GIT_SOURCE_BRANCH=$(jq -r .pull_request.head.ref $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
      - run: git clone -q --depth=1 --branch=$GIT_SOURCE_BRANCH https://github.com/$GITHUB_OWNER/$GITHUB_REPO.git repository
      - working-directory: repository
        run: /bin/bash $RESOURCES_PATH/bash/workflow/verify.sh
