name: Prepare workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_OWNER: StanleyProjects
      GITHUB_REPO: AndroidExtension.UserInterface
      GITHUB_PAT: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      RESOURCES_PATH: buildSrc/src/main/resources
    steps:
      - run: |
          echo "HOME=$(echo ~)" >> $GITHUB_ENV
          echo "DOCKER_PREFIX=docker_${GITHUB_RUN_NUMBER}_${GITHUB_RUN_ID}" >> $GITHUB_ENV
          echo "ASSEMBLY_PATH=$HOME/assembly_${GITHUB_RUN_NUMBER}_${GITHUB_RUN_ID}" >> $GITHUB_ENV
      - if: github.event_name == 'pull_request'
        run: echo "GIT_COMMIT_SHA=$(jq -r .pull_request.head.sha $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
      - run: git clone --depth=1 --branch=$GIT_SOURCE_BRANCH https://github.com/$GITHUB_OWNER/$GITHUB_REPO.git $HOME/repository
      - working-directory: ${{env.HOME}}/repository
        run: |
          /bin/bash $RESOURCES_PATH/bash/workflow/assemble/vcs.sh
          /bin/bash $RESOURCES_PATH/bash/workflow/prepare.sh
